import React from 'react';
import { Container } from "./styles";
import githubIcon from "../../assets/github.svg";
import ScrollAnimation from "react-animate-on-scroll";
export function Project() {
    return (React.createElement(Container, { id: "project" },
        React.createElement("h2", null, "My Projects"),
        React.createElement("div", { className: "projects" },
            React.createElement(ScrollAnimation, { animateIn: "flipInX" },
                React.createElement("div", { className: "project" },
                    React.createElement("header", null,
                        React.createElement("svg", { width: "50", xmlns: "http://www.w3.org/2000/svg", role: "img", viewBox: "0 0 24 24", fill: "none", stroke: "#23ce6b ", "stroke-width": "1", "stroke-linecap": "round", "stroke-linejoin": "round" },
                            React.createElement("title", null, "Folder"),
                            React.createElement("path", { d: "M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z" })),
                        React.createElement("div", { className: "project-links center-image" },
                            React.createElement("a", { href: "https://github.com/Shanthapriya23/Design_Genie_FYP_Phase1.git", target: "_blank", rel: "noreferrer" },
                                React.createElement("img", { src: githubIcon, style: { float: "right" }, alt: "Visit site" })))),
                    React.createElement("div", { className: "body" },
                        React.createElement("h3", null, "Design Genie"),
                        React.createElement("p", null, "An AI-powered creative assistant that generates personalized event posters effortlessly with enhanced prompts, dynamic scenes, and catchy slogans using Stable Diffusion and NLP.")),
                    React.createElement("footer", null,
                        React.createElement("ul", { className: "tech-list" },
                            React.createElement("li", null, "Python, Stable Diffusion, NLP, AI/ML"))))),
            React.createElement(ScrollAnimation, { animateIn: "flipInX" },
                React.createElement("div", { className: "project" },
                    React.createElement("header", null,
                        React.createElement("svg", { width: "50", xmlns: "http://www.w3.org/2000/svg", role: "img", viewBox: "0 0 24 24", fill: "none", stroke: "#23ce6b ", "stroke-width": "1", "stroke-linecap": "round", "stroke-linejoin": "round" },
                            React.createElement("title", null, "Folder"),
                            React.createElement("path", { d: "M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z" })),
                        React.createElement("div", { className: "project-links center-image" },
                            React.createElement("a", { href: "https://github.com/Shanthapriya23/srp_oral_cancer.git", target: "_blank", rel: "noreferrer" },
                                React.createElement("img", { src: githubIcon, style: { float: "right" }, alt: "Visit site" })))),
                    React.createElement("div", { className: "body" },
                        React.createElement("h3", null, "Oral Cancer Risk Analysis"),
                        React.createElement("p", null, "Developed an oral cancer risk analysis system using Convolutional Neural Networks (CNNs) for lesion image analysis and Random Forest algorithms for evaluating clinical data, integrating both methods to provide a comprehensive risk assessment.")),
                    React.createElement("footer", null,
                        React.createElement("ul", { className: "tech-list" },
                            React.createElement("li", null, "Python, CNN, Random Forest, Deep Learning"))))),
            React.createElement(ScrollAnimation, { animateIn: "flipInX" },
                React.createElement("div", { className: "project" },
                    React.createElement("header", null,
                        React.createElement("svg", { width: "50", xmlns: "http://www.w3.org/2000/svg", role: "img", viewBox: "0 0 24 24", fill: "none", stroke: "#23ce6b ", "stroke-width": "1", "stroke-linecap": "round", "stroke-linejoin": "round" },
                            React.createElement("title", null, "Folder"),
                            React.createElement("path", { d: "M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z" })),
                        React.createElement("div", { className: "project-links center-image" },
                            React.createElement("a", { href: "https://github.com/Shanthapriya23/IOT-Smart-Kitchen-System", target: "_blank", rel: "noreferrer" },
                                React.createElement("img", { src: githubIcon, style: { float: "right" }, alt: "Visit site" })))),
                    React.createElement("div", { className: "body" },
                        React.createElement("h3", null, "IOT Based Smart Kitchen System"),
                        React.createElement("p", null, "A Smart Kitchen System using MQ-2 Gas Sensor for early gas leak detection and an HX711 Load Cell for real-time LPG weight monitoring. Improves kitchen safety by detecting gas leaks instantly and helps users track LPG consumption effortlessly.")),
                    React.createElement("footer", null,
                        React.createElement("ul", { className: "tech-list" },
                            React.createElement("li", null, "IoT, Arduino, MQ-2 Sensor, HX711 Load Cell"))))),
            React.createElement(ScrollAnimation, { animateIn: "flipInX" },
                React.createElement("div", { className: "project" },
                    React.createElement("header", null,
                        React.createElement("svg", { width: "50", xmlns: "http://www.w3.org/2000/svg", role: "img", viewBox: "0 0 24 24", fill: "none", stroke: "#23ce6b ", "stroke-width": "1", "stroke-linecap": "round", "stroke-linejoin": "round" },
                            React.createElement("title", null, "Folder"),
                            React.createElement("path", { d: "M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z" })),
                        React.createElement("div", { className: "project-links center-image" },
                            React.createElement("a", { href: "https://github.com/Shanthapriya23/Skill-Bridge-360", target: "_blank", rel: "noreferrer" },
                                React.createElement("img", { src: githubIcon, style: { float: "right" }, alt: "Visit site" })))),
                    React.createElement("div", { className: "body" },
                        React.createElement("h3", null, "Skill Bridge 360"),
                        React.createElement("p", null, "An AI-powered multimodal platform that bridges language and accessibility gaps in education through automated vernacular dubbing, intelligent summarization, and interactive learning tools.")),
                    React.createElement("footer", null,
                        React.createElement("ul", { className: "tech-list" },
                            React.createElement("li", null, "Python, AI/ML, NLP, Speech Processing"))))),
            React.createElement(ScrollAnimation, { animateIn: "flipInX" },
                React.createElement("div", { className: "project" },
                    React.createElement("header", null,
                        React.createElement("svg", { width: "50", xmlns: "http://www.w3.org/2000/svg", role: "img", viewBox: "0 0 24 24", fill: "none", stroke: "#23ce6b ", "stroke-width": "1", "stroke-linecap": "round", "stroke-linejoin": "round" },
                            React.createElement("title", null, "Folder"),
                            React.createElement("path", { d: "M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z" })),
                        React.createElement("div", { className: "project-links center-image" },
                            React.createElement("a", { href: "https://github.com/Shanthapriya23/Culinary_canvas", target: "_blank", rel: "noreferrer" },
                                React.createElement("img", { src: githubIcon, style: { float: "right" }, alt: "Visit site" })))),
                    React.createElement("div", { className: "body" },
                        React.createElement("h3", null, "Culinary Canvas"),
                        React.createElement("p", null, "Developed the Culinary Canvas restaurant website using Java JSP Servlets to enable online ordering. Implemented features for users to add items to their cart, process online payments, enter delivery addresses, and arrange order deliveries.")),
                    React.createElement("footer", null,
                        React.createElement("ul", { className: "tech-list" },
                            React.createElement("li", null, "Java Servlets, Apache Tomcat, HTML, CSS, MySQL"))))),
            React.createElement(ScrollAnimation, { animateIn: "flipInX" },
                React.createElement("div", { className: "project" },
                    React.createElement("header", null,
                        React.createElement("svg", { width: "50", xmlns: "http://www.w3.org/2000/svg", role: "img", viewBox: "0 0 24 24", fill: "none", stroke: "#23ce6b ", "stroke-width": "1", "stroke-linecap": "round", "stroke-linejoin": "round" },
                            React.createElement("title", null, "Folder"),
                            React.createElement("path", { d: "M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z" })),
                        React.createElement("div", { className: "project-links center-image" },
                            React.createElement("a", { href: "https://github.com/Shanthapriya23/event_management_website", target: "_blank", rel: "noreferrer" },
                                React.createElement("img", { src: githubIcon, style: { float: "right" }, alt: "Visit site" })))),
                    React.createElement("div", { className: "body" },
                        React.createElement("h3", null, "Event Management Platform"),
                        React.createElement("p", null, "A web development project that bridges the gap between event hosts and the audience. Built using PostgreSQL, PHP, JavaScript, HTML and CSS for seamless event coordination.")),
                    React.createElement("footer", null,
                        React.createElement("ul", { className: "tech-list" },
                            React.createElement("li", null, "HTML, CSS, JavaScript, Bootstrap, PHP, PostgreSQL"))))),
            React.createElement(ScrollAnimation, { animateIn: "flipInX" },
                React.createElement("div", { className: "project" },
                    React.createElement("header", null,
                        React.createElement("svg", { width: "50", xmlns: "http://www.w3.org/2000/svg", role: "img", viewBox: "0 0 24 24", fill: "none", stroke: "#23ce6b ", "stroke-width": "1", "stroke-linecap": "round", "stroke-linejoin": "round" },
                            React.createElement("title", null, "Folder"),
                            React.createElement("path", { d: "M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z" })),
                        React.createElement("div", { className: "project-links center-image" },
                            React.createElement("a", { href: "https://github.com/Shanthapriya23/Student_db_management", target: "_blank", rel: "noreferrer" },
                                React.createElement("img", { src: githubIcon, style: { float: "right" }, alt: "Visit site" })))),
                    React.createElement("div", { className: "body" },
                        React.createElement("h3", null, "Student Details Management"),
                        React.createElement("p", null, "A project aimed at maintaining student details in a college database using basic CRUD (Create, Read, Update, Delete) operations. Built for the IT Essentials Laboratory using web technologies.")),
                    React.createElement("footer", null,
                        React.createElement("ul", { className: "tech-list" },
                            React.createElement("li", null, "HTML, CSS, PHP, JavaScript, MySQL"))))),
            React.createElement(ScrollAnimation, { animateIn: "flipInX" },
                React.createElement("div", { className: "project" },
                    React.createElement("header", null,
                        React.createElement("svg", { width: "50", xmlns: "http://www.w3.org/2000/svg", role: "img", viewBox: "0 0 24 24", fill: "none", stroke: "#23ce6b ", "stroke-width": "1", "stroke-linecap": "round", "stroke-linejoin": "round" },
                            React.createElement("title", null, "Folder"),
                            React.createElement("path", { d: "M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z" })),
                        React.createElement("div", { className: "project-links center-image" },
                            React.createElement("a", { href: "https://github.com/Shanthapriya23/Insight_complete_with_backend", target: "_blank", rel: "noreferrer" },
                                React.createElement("img", { src: githubIcon, style: { float: "right" }, alt: "Visit site" })))),
                                React.createElement("div", { className: "body" },
                                    React.createElement("h3", null, "Insight Arithmetic"),
                                    React.createElement("p", null, "Insight is a Web platform to teach the middle school students the concepts and techniques of Ancient Vedic Mathematics ,which would help the students by reducing the time consumed in calculation ,there by making mental makes more easier and comfortable to students.")),
                                React.createElement("footer", null,
                                    React.createElement("ul", { className: "tech-list" },
                                        React.createElement("li", null, "HTML, CSS, JavaScript, Bootstrap, PHP, MySQL"))))),
                                        React.createElement(ScrollAnimation, { animateIn: "flipInX" },
                                        React.createElement("div", { className: "project" },
                                            React.createElement("header", null,
                                                React.createElement("svg", { width: "50", xmlns: "http://www.w3.org/2000/svg", role: "img", viewBox: "0 0 24 24", fill: "none", stroke: "#23ce6b ", "stroke-width": "1", "stroke-linecap": "round", "stroke-linejoin": "round" },
                                                    React.createElement("title", null, "Folder"),
                                                    React.createElement("path", { d: "M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z" })),
                                                React.createElement("div", { className: "project-links center-image" },
                                                    React.createElement("a", { href: "https://github.com/Shanthapriya23/Shantha_priya_portfolio", target: "_blank", rel: "noreferrer" },
                                                        React.createElement("img", { src: githubIcon, style: { float: "right" }, alt: "Visit site" })))),
                                            React.createElement("div", { className: "body" },
                                                React.createElement("h3", null, "My personal Portfolio"),
                                                React.createElement("p", null, "My personalized and customized portfolio to display my interests, skills, projects and talents")),
                                            React.createElement("footer", null,
                                                React.createElement("ul", { className: "tech-list" },
                                                    React.createElement("li", null, "Type Script,React js,BootStrap,Mediaquery,HTML,CSS"))))),)));}
            