import styled from "styled-components";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};

export var Container = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  margin-top: 3rem;\n  display: grid;\n  place-items: center;\n  h2{\n    text-align: center;\n    margin-bottom: 2rem;\n  }\n  form{\n    display: flex;\n    flex-direction: column;\n    text-align: center;\n    align-items: center;\n    gap: 1rem;\n    width: 100%;\n    input, textarea{\n      width: 60rem;\n      padding: 1rem 2rem;\n      border-radius: 1.6rem;\n      outline: none;\n      border: none;\n      background:none;\n      border: 1px solid #FFF;\n      color: white;\n      font-weight: 600;\n      &::placeholder{\n        color: #FFF;\n      }\n    }\n\n    textarea{\n      height: 20rem;\n      overflow-y: auto;\n      resize: none;\n    }\n\n    button{\n      padding: 1rem 6rem;\n      text-transform: uppercase;\n    }\n  \n  }\n\n  @media (max-width: 740px){\n    form{\n      width: 100%;\n      \n      input,textarea{\n        width: 100%;\n      }\n    }\n  }\n"], ["\n  margin-top: 3rem;\n  display: grid;\n  place-items: center;\n  h2{\n    text-align: center;\n    margin-bottom: 2rem;\n  }\n  form{\n    display: flex;\n    flex-direction: column;\n    text-align: center;\n    align-items: center;\n    gap: 1rem;\n    width: 100%;\n    input, textarea{\n      width: 60rem;\n      padding: 1rem 2rem;\n      border-radius: 1.6rem;\n      outline: none;\n      border: none;\n      background:none;\n      border: 1px solid #FFF;\n      color: white;\n      font-weight: 600;\n      &::placeholder{\n        color: #FFF;\n      }\n    }\n\n    textarea{\n      height: 20rem;\n      overflow-y: auto;\n      resize: none;\n    }\n\n    button{\n      padding: 1rem 6rem;\n      text-transform: uppercase;\n    }\n  \n  }\n\n  @media (max-width: 740px){\n    form{\n      width: 100%;\n      \n      input,textarea{\n        width: 100%;\n      }\n    }\n  }\n"])));
export var ContainerSucces = styled.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  margin-top: 10rem;\n  text-align: center;\n\n  button{\n    border-radius: 0.6rem;\n    padding: 1rem;\n    margin-top: 0.8rem;\n    text-transform: uppercase;\n    text-align: center;\n    color: #fbfbfb;\n  }\n"], ["\n  margin-top: 10rem;\n  text-align: center;\n\n  button{\n    border-radius: 0.6rem;\n    padding: 1rem;\n    margin-top: 0.8rem;\n    text-transform: uppercase;\n    text-align: center;\n    color: #fbfbfb;\n  }\n"])));
var templateObject_1, templateObject_2;
